const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..');
const FRP_ROOT = path.join(REPO_ROOT, 'frp');
const FRP_CONF_DIR = path.join(FRP_ROOT, 'conf');
const DEFAULT_FRP_MODE = 'disabled';
const DEFAULT_SETUP_MODE = 'client';
const DEFAULT_FRP_TYPE = 'ip';
const DEFAULT_SERVER_PORT = 7000;
const DEFAULT_LOCAL_IP = '127.0.0.1';
const DEFAULT_LOCAL_PORT = 8083;

function readEnvFile(envPath = path.join(REPO_ROOT, '.env'), baseEnv = process.env) {
  const env = { ...baseEnv };
  if (!fs.existsSync(envPath)) return env;
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const m = line.match(/^([^#=]+)=(.*)$/);
    if (m && env[m[1].trim()] === undefined) env[m[1].trim()] = m[2].trim();
  }
  return env;
}

function envValue(env, name, fallback = '') {
  const raw = env[name];
  if (raw === undefined || raw === null) return fallback;
  const value = String(raw).trim();
  return value || fallback;
}

function normalizeMode(value, defaultMode = DEFAULT_FRP_MODE) {
  const mode = String(value || defaultMode).trim().toLowerCase();
  if (!['disabled', 'client', 'server'].includes(mode)) {
    throw new Error(`FRP_MODE must be disabled, client, or server`);
  }
  return mode;
}

function normalizeType(value) {
  const type = String(value || DEFAULT_FRP_TYPE).trim().toLowerCase();
  if (!['ip', 'domain'].includes(type)) throw new Error('FRP_TYPE must be ip or domain');
  return type;
}

function parsePort(value, name, fallback) {
  const raw = envValue({ value }, 'value', fallback === undefined ? '' : String(fallback));
  if (!/^\d+$/.test(raw)) throw new Error(`${name} must be an integer port from 1 to 65535`);
  const port = Number(raw);
  if (!Number.isSafeInteger(port) || port < 1 || port > 65535) {
    throw new Error(`${name} must be an integer port from 1 to 65535`);
  }
  return port;
}

function tomlString(value) {
  return JSON.stringify(String(value));
}

function numericOrPlaceholder(value, placeholder) {
  const raw = String(value || '').trim();
  if (!raw) return placeholder;
  if (/^\d+$/.test(raw)) return Number(raw);
  return raw;
}

function renderTomlValue(value) {
  if (typeof value === 'number') return String(value);
  return String(value);
}

function defaultConfigPath(mode) {
  return path.join(FRP_CONF_DIR, mode === 'server' ? 'frps.toml' : 'frpc.toml');
}

function resolveFrpConfig(env = process.env, options = {}) {
  const hasFrpIntent = Object.keys(env).some((key) => key.startsWith('FRP_') && key !== 'FRP_AUTO_START');
  const defaultMode = options.defaultMode || (hasFrpIntent ? DEFAULT_SETUP_MODE : DEFAULT_FRP_MODE);
  const mode = normalizeMode(envValue(env, 'FRP_MODE', defaultMode), defaultMode);
  const type = normalizeType(envValue(env, 'FRP_TYPE', DEFAULT_FRP_TYPE));
  const configPath = envValue(env, 'FRP_CONFIG_FILE', defaultConfigPath(mode));
  const token = envValue(env, 'FRP_TOKEN', 'YOUR_FRP_TOKEN');
  const localIP = envValue(env, 'FRP_LOCAL_IP', DEFAULT_LOCAL_IP);
  const localPort = parsePort(envValue(env, 'FRP_LOCAL_PORT', String(DEFAULT_LOCAL_PORT)), 'FRP_LOCAL_PORT', DEFAULT_LOCAL_PORT);
  const serverPort = parsePort(envValue(env, 'FRP_SERVER_PORT', String(DEFAULT_SERVER_PORT)), 'FRP_SERVER_PORT', DEFAULT_SERVER_PORT);
  const bindPort = parsePort(envValue(env, 'FRP_BIND_PORT', String(serverPort)), 'FRP_BIND_PORT', serverPort);
  const vhostHTTPPort = envValue(env, 'FRP_VHOST_HTTP_PORT', '');
  const extraTomlFromFile = env.FRP_EXTRA_TOML_FILE
    ? fs.readFileSync(path.resolve(String(env.FRP_EXTRA_TOML_FILE)), 'utf8')
    : '';
  const extraToml = [envValue(env, 'FRP_EXTRA_TOML', ''), extraTomlFromFile].filter(Boolean).join('\n');

  return {
    mode,
    type,
    binaryName: mode === 'server' ? 'frps' : 'frpc',
    configPath,
    serverAddr: envValue(env, 'FRP_SERVER_ADDR', 'YOUR_FRP_SERVER_IP'),
    serverPort,
    token,
    localIP,
    localPort,
    publicPort: numericOrPlaceholder(envValue(env, 'FRP_PUBLIC_PORT', ''), 'YOUR_PUBLIC_PORT'),
    customDomain: envValue(env, 'FRP_CUSTOM_DOMAIN', 'YOUR_DOMAIN'),
    subdomain: envValue(env, 'FRP_SUBDOMAIN', ''),
    bindPort,
    vhostHTTPPort: vhostHTTPPort ? parsePort(vhostHTTPPort, 'FRP_VHOST_HTTP_PORT') : null,
    extraToml,
  };
}

function renderClientToml(config) {
  const lines = [
    '# Generated by cc-web-enhance frp setup. Do not commit this file.',
    `serverAddr = ${tomlString(config.serverAddr)}`,
    `serverPort = ${config.serverPort}`,
    '',
    'auth.method = "token"',
    `auth.token = ${tomlString(config.token)}`,
    '',
    '[[proxies]]',
    `name = ${tomlString(config.type === 'domain' ? 'cc-web-enhance-domain' : 'cc-web-enhance-ip')}`,
    `type = ${tomlString(config.type === 'domain' ? 'http' : 'tcp')}`,
    `localIP = ${tomlString(config.localIP)}`,
    `localPort = ${config.localPort}`,
  ];
  if (config.type === 'domain') {
    if (config.subdomain) lines.push(`subdomain = ${tomlString(config.subdomain)}`);
    else lines.push(`customDomains = [${tomlString(config.customDomain)}]`);
  } else {
    lines.push(`remotePort = ${renderTomlValue(config.publicPort)}`);
  }
  if (config.extraToml) lines.push('', '# Native frp passthrough', config.extraToml.trim());
  lines.push('');
  return `${lines.join('\n')}\n`;
}

function renderServerToml(config) {
  const lines = [
    '# Generated by cc-web-enhance frp setup. Do not commit this file.',
    `bindPort = ${config.bindPort}`,
    '',
    'auth.method = "token"',
    `auth.token = ${tomlString(config.token)}`,
  ];
  if (config.vhostHTTPPort) lines.push('', `vhostHTTPPort = ${config.vhostHTTPPort}`);
  if (config.extraToml) lines.push('', '# Native frp passthrough', config.extraToml.trim());
  lines.push('');
  return `${lines.join('\n')}\n`;
}

function renderFrpToml(config) {
  if (config.mode === 'disabled') return '';
  return config.mode === 'server' ? renderServerToml(config) : renderClientToml(config);
}

function hasPlaceholders(content) {
  return /\bYOUR_[A-Z0-9_]+\b/.test(content);
}

function writeFrpConfig(config) {
  if (config.mode === 'disabled') {
    return { skipped: true, configPath: config.configPath, content: '' };
  }
  const content = renderFrpToml(config);
  fs.mkdirSync(path.dirname(config.configPath), { recursive: true });
  fs.writeFileSync(config.configPath, content);
  return {
    skipped: false,
    configPath: config.configPath,
    content,
    hasPlaceholders: hasPlaceholders(content),
  };
}

module.exports = {
  DEFAULT_FRP_MODE,
  DEFAULT_FRP_TYPE,
  DEFAULT_LOCAL_IP,
  DEFAULT_LOCAL_PORT,
  DEFAULT_SERVER_PORT,
  defaultConfigPath,
  hasPlaceholders,
  readEnvFile,
  renderFrpToml,
  resolveFrpConfig,
  writeFrpConfig,
};
